/**
 * Comprehensive VRL Function Registry
 * Contains all VRL functions with signatures, documentation, and fallibility information
 */

export interface VrlFunctionParameter {
    name: string;
    type: string;
    optional?: boolean;
    defaultValue?: string;
}

export interface VrlFunction {
    name: string;
    parameters: VrlFunctionParameter[];
    returnType: string;
    fallible: boolean;
    description: string;
    category: string;
    example?: string;
}

export const VRL_FUNCTIONS: { [key: string]: VrlFunction } = {
    // Array Functions
    pop: {
        name: 'pop',
        parameters: [{ name: 'value', type: 'array' }],
        returnType: 'array',
        fallible: false,
        description: 'Removes the last item from the array and returns it',
        category: 'array',
        example: 'pop([1, 2, 3]) // [1, 2]',
    },
    zip: {
        name: 'zip',
        parameters: [
            { name: 'array_0', type: 'array' },
            { name: 'array_1', type: 'array', optional: true },
        ],
        returnType: 'array',
        fallible: true,
        description: 'Iterates over several arrays in parallel, producing a new array of arrays',
        category: 'array',
        example: 'zip!([1, 2], ["a", "b"]) // [[1, "a"], [2, "b"]]',
    },
    append: {
        name: 'append',
        parameters: [
            { name: 'value', type: 'array' },
            { name: 'items', type: 'array' },
        ],
        returnType: 'array',
        fallible: false,
        description: 'Appends items from one array to another',
        category: 'array',
        example: 'append([1, 2], [3, 4]) // [1, 2, 3, 4]',
    },
    chunks: {
        name: 'chunks',
        parameters: [
            { name: 'value', type: 'array' },
            { name: 'chunk_size', type: 'int' },
        ],
        returnType: 'array',
        fallible: false,
        description: 'Splits an array into chunks of specified size',
        category: 'array',
        example: 'chunks([1, 2, 3, 4], 2) // [[1, 2], [3, 4]]',
    },
    compact: {
        name: 'compact',
        parameters: [{ name: 'value', type: 'array' }],
        returnType: 'array',
        fallible: false,
        description: 'Removes null values from an array',
        category: 'array',
        example: 'compact([1, null, 2, null, 3]) // [1, 2, 3]',
    },
    filter: {
        name: 'filter',
        parameters: [
            { name: 'value', type: 'array' },
            { name: 'condition', type: 'closure' },
        ],
        returnType: 'array',
        fallible: false,
        description: 'Filters array elements based on a condition',
        category: 'array',
        example: 'filter([1, 2, 3, 4], { |item| item > 2 }) // [3, 4]',
    },
    flatten: {
        name: 'flatten',
        parameters: [
            { name: 'value', type: 'array' },
            { name: 'depth', type: 'int', optional: true },
        ],
        returnType: 'array',
        fallible: false,
        description: 'Flattens nested arrays to specified depth',
        category: 'array',
        example: 'flatten([[1, 2], [3, [4, 5]]]) // [1, 2, 3, [4, 5]]',
    },
    join: {
        name: 'join',
        parameters: [
            { name: 'value', type: 'array' },
            { name: 'separator', type: 'string' },
        ],
        returnType: 'string',
        fallible: true,
        description: 'Joins array elements into a string with separator',
        category: 'array',
        example: 'join!([1, 2, 3], ",") // "1,2,3"',
    },
    length: {
        name: 'length',
        parameters: [{ name: 'value', type: 'array|object|string' }],
        returnType: 'int',
        fallible: false,
        description: 'Returns the length of an array, object, or string',
        category: 'array',
        example: 'length([1, 2, 3]) // 3',
    },
    push: {
        name: 'push',
        parameters: [
            { name: 'value', type: 'array' },
            { name: 'item', type: 'any' },
        ],
        returnType: 'array',
        fallible: false,
        description: 'Adds an item to the end of an array',
        category: 'array',
        example: 'push([1, 2], 3) // [1, 2, 3]',
    },
    reverse: {
        name: 'reverse',
        parameters: [{ name: 'value', type: 'array' }],
        returnType: 'array',
        fallible: false,
        description: 'Reverses the order of array elements',
        category: 'array',
        example: 'reverse([1, 2, 3]) // [3, 2, 1]',
    },
    slice: {
        name: 'slice',
        parameters: [
            { name: 'value', type: 'array' },
            { name: 'start', type: 'int' },
            { name: 'end', type: 'int', optional: true },
        ],
        returnType: 'array',
        fallible: false,
        description: 'Extracts a portion of an array',
        category: 'array',
        example: 'slice([1, 2, 3, 4], 1, 3) // [2, 3]',
    },
    sort: {
        name: 'sort',
        parameters: [{ name: 'value', type: 'array' }],
        returnType: 'array',
        fallible: false,
        description: 'Sorts array elements',
        category: 'array',
        example: 'sort([3, 1, 2]) // [1, 2, 3]',
    },
    unique: {
        name: 'unique',
        parameters: [{ name: 'value', type: 'array' }],
        returnType: 'array',
        fallible: false,
        description: 'Returns unique elements from an array',
        category: 'array',
        example: 'unique([1, 2, 2, 3]) // [1, 2, 3]',
    },

    // Codec Functions (Encoding/Decoding)
    decode_base16: {
        name: 'decode_base16',
        parameters: [{ name: 'value', type: 'string' }],
        returnType: 'string',
        fallible: true,
        description: 'Decodes a base16 encoded string',
        category: 'codec',
        example: 'decode_base16!("48656C6C6F") // "Hello"',
    },
    decode_base64: {
        name: 'decode_base64',
        parameters: [{ name: 'value', type: 'string' }],
        returnType: 'string',
        fallible: true,
        description: 'Decodes a base64 encoded string',
        category: 'codec',
        example: 'decode_base64!("SGVsbG8=") // "Hello"',
    },
    decode_gzip: {
        name: 'decode_gzip',
        parameters: [{ name: 'value', type: 'string' }],
        returnType: 'string',
        fallible: true,
        description: 'Decompresses a gzip compressed string',
        category: 'codec',
        example: 'decode_gzip!(.compressed_data)',
    },
    decode_percent: {
        name: 'decode_percent',
        parameters: [{ name: 'value', type: 'string' }],
        returnType: 'string',
        fallible: true,
        description: 'Decodes a percent-encoded (URL-encoded) string',
        category: 'codec',
        example: 'decode_percent!("Hello%20World") // "Hello World"',
    },
    encode_base16: {
        name: 'encode_base16',
        parameters: [{ name: 'value', type: 'string' }],
        returnType: 'string',
        fallible: false,
        description: 'Encodes a string as base16',
        category: 'codec',
        example: 'encode_base16("Hello") // "48656C6C6F"',
    },
    encode_base64: {
        name: 'encode_base64',
        parameters: [{ name: 'value', type: 'string' }],
        returnType: 'string',
        fallible: false,
        description: 'Encodes a string as base64',
        category: 'codec',
        example: 'encode_base64("Hello") // "SGVsbG8="',
    },
    encode_gzip: {
        name: 'encode_gzip',
        parameters: [
            { name: 'value', type: 'string' },
            { name: 'level', type: 'int', optional: true },
        ],
        returnType: 'string',
        fallible: true,
        description: 'Compresses a string using gzip',
        category: 'codec',
        example: 'encode_gzip!("Hello World")',
    },
    encode_percent: {
        name: 'encode_percent',
        parameters: [
            { name: 'value', type: 'string' },
            { name: 'ascii_only', type: 'bool', optional: true },
        ],
        returnType: 'string',
        fallible: false,
        description: 'Encodes a string with percent encoding (URL encoding)',
        category: 'codec',
        example: 'encode_percent("Hello World") // "Hello%20World"',
    },
    decode_charset: {
        name: 'decode_charset',
        parameters: [
            { name: 'value', type: 'string' },
            { name: 'from_charset', type: 'string' },
        ],
        returnType: 'string',
        fallible: true,
        description: 'Decodes a string from a specified character set to UTF-8',
        category: 'codec',
        example: 'decode_charset!(.value, "iso-8859-1")',
    },
    decode_lz4: {
        name: 'decode_lz4',
        parameters: [{ name: 'value', type: 'string' }],
        returnType: 'string',
        fallible: true,
        description: 'Decompresses an LZ4-compressed string',
        category: 'codec',
        example: 'decode_lz4!(.compressed)',
    },
    decode_mime_q: {
        name: 'decode_mime_q',
        parameters: [{ name: 'value', type: 'string' }],
        returnType: 'string',
        fallible: true,
        description: 'Decodes a MIME "Q" encoded string',
        category: 'codec',
        example: 'decode_mime_q!("=?utf-8?Q?Hello=20World?=")',
    },
    decode_punycode: {
        name: 'decode_punycode',
        parameters: [{ name: 'value', type: 'string' }],
        returnType: 'string',
        fallible: true,
        description: 'Decodes a Punycode-encoded domain name to Unicode',
        category: 'codec',
        example: 'decode_punycode!("xn--nxasmq6b.com")',
    },
    decode_snappy: {
        name: 'decode_snappy',
        parameters: [{ name: 'value', type: 'string' }],
        returnType: 'string',
        fallible: true,
        description: 'Decompresses a Snappy-compressed string',
        category: 'codec',
        example: 'decode_snappy!(.compressed)',
    },
    decode_zlib: {
        name: 'decode_zlib',
        parameters: [{ name: 'value', type: 'string' }],
        returnType: 'string',
        fallible: true,
        description: 'Decompresses a zlib-compressed string',
        category: 'codec',
        example: 'decode_zlib!(.compressed)',
    },
    decode_zstd: {
        name: 'decode_zstd',
        parameters: [{ name: 'value', type: 'string' }],
        returnType: 'string',
        fallible: true,
        description: 'Decompresses a Zstandard-compressed string',
        category: 'codec',
        example: 'decode_zstd!(.compressed)',
    },
    encode_charset: {
        name: 'encode_charset',
        parameters: [
            { name: 'value', type: 'string' },
            { name: 'to_charset', type: 'string' },
        ],
        returnType: 'string',
        fallible: true,
        description: 'Encodes a UTF-8 string to a specified character set',
        category: 'codec',
        example: 'encode_charset!("Hello", "iso-8859-1")',
    },
    encode_json: {
        name: 'encode_json',
        parameters: [
            { name: 'value', type: 'any' },
            { name: 'pretty', type: 'bool', optional: true },
        ],
        returnType: 'string',
        fallible: false,
        description: 'Encodes a value to JSON string',
        category: 'codec',
        example: 'encode_json({"key": "value"}) // "{\"key\":\"value\"}"',
    },
    encode_key_value: {
        name: 'encode_key_value',
        parameters: [
            { name: 'value', type: 'object' },
            { name: 'fields_ordering', type: 'array', optional: true },
            { name: 'key_value_delimiter', type: 'string', optional: true },
            { name: 'field_delimiter', type: 'string', optional: true },
            { name: 'flatten_boolean', type: 'bool', optional: true },
        ],
        returnType: 'string',
        fallible: true,
        description: 'Encodes an object into key=value formatted string',
        category: 'codec',
        example: 'encode_key_value!({"key": "value", "num": 1})',
    },
    encode_logfmt: {
        name: 'encode_logfmt',
        parameters: [
            { name: 'value', type: 'object' },
            { name: 'fields_ordering', type: 'array', optional: true },
        ],
        returnType: 'string',
        fallible: true,
        description: 'Encodes an object as logfmt formatted string',
        category: 'codec',
        example: 'encode_logfmt!({"level": "info", "msg": "hello"})',
    },
    encode_lz4: {
        name: 'encode_lz4',
        parameters: [{ name: 'value', type: 'string' }],
        returnType: 'string',
        fallible: false,
        description: 'Compresses a string using LZ4',
        category: 'codec',
        example: 'encode_lz4("Hello World")',
    },
    encode_proto: {
        name: 'encode_proto',
        parameters: [
            { name: 'value', type: 'any' },
            { name: 'desc_file', type: 'string' },
            { name: 'message_type', type: 'string' },
        ],
        returnType: 'string',
        fallible: true,
        description: 'Encodes a value as a Protocol Buffers payload',
        category: 'codec',
        example: 'encode_proto!(.data, "/path/to/schema.pb", "MyMessage")',
    },
    encode_punycode: {
        name: 'encode_punycode',
        parameters: [{ name: 'value', type: 'string' }],
        returnType: 'string',
        fallible: true,
        description: 'Encodes a Unicode domain name to Punycode',
        category: 'codec',
        example: 'encode_punycode!("münchen.de")',
    },
    encode_snappy: {
        name: 'encode_snappy',
        parameters: [{ name: 'value', type: 'string' }],
        returnType: 'string',
        fallible: false,
        description: 'Compresses a string using Snappy',
        category: 'codec',
        example: 'encode_snappy("Hello World")',
    },
    encode_zlib: {
        name: 'encode_zlib',
        parameters: [
            { name: 'value', type: 'string' },
            { name: 'level', type: 'int', optional: true },
        ],
        returnType: 'string',
        fallible: false,
        description: 'Compresses a string using zlib',
        category: 'codec',
        example: 'encode_zlib("Hello World")',
    },
    encode_zstd: {
        name: 'encode_zstd',
        parameters: [
            { name: 'value', type: 'string' },
            { name: 'level', type: 'int', optional: true },
        ],
        returnType: 'string',
        fallible: false,
        description: 'Compresses a string using Zstandard',
        category: 'codec',
        example: 'encode_zstd("Hello World")',
    },

    // Convert Functions (syslog)
    to_syslog_facility: {
        name: 'to_syslog_facility',
        parameters: [{ name: 'value', type: 'int' }],
        returnType: 'string',
        fallible: true,
        description: 'Converts a syslog facility code (integer) to its string name',
        category: 'convert',
        example: 'to_syslog_facility!(0) // "kern"',
    },
    to_syslog_facility_code: {
        name: 'to_syslog_facility_code',
        parameters: [{ name: 'value', type: 'string' }],
        returnType: 'int',
        fallible: true,
        description: 'Converts a syslog facility string name to its integer code',
        category: 'convert',
        example: 'to_syslog_facility_code!("kern") // 0',
    },
    to_syslog_level: {
        name: 'to_syslog_level',
        parameters: [{ name: 'value', type: 'int' }],
        returnType: 'string',
        fallible: true,
        description: 'Converts a syslog severity integer to a log level string',
        category: 'convert',
        example: 'to_syslog_level!(3) // "err"',
    },
    to_syslog_severity: {
        name: 'to_syslog_severity',
        parameters: [{ name: 'value', type: 'string' }],
        returnType: 'int',
        fallible: true,
        description: 'Converts a syslog log level string to its severity integer',
        category: 'convert',
        example: 'to_syslog_severity!("err") // 3',
    },

    // Coerce/Type Conversion Functions
    to_bool: {
        name: 'to_bool',
        parameters: [{ name: 'value', type: 'any' }],
        returnType: 'bool',
        fallible: true,
        description: 'Converts a value to boolean',
        category: 'coerce',
        example: 'to_bool!("true") // true',
    },
    to_float: {
        name: 'to_float',
        parameters: [{ name: 'value', type: 'any' }],
        returnType: 'float',
        fallible: true,
        description: 'Converts a value to float',
        category: 'coerce',
        example: 'to_float!("3.14") // 3.14',
    },
    to_int: {
        name: 'to_int',
        parameters: [{ name: 'value', type: 'any' }],
        returnType: 'int',
        fallible: true,
        description: 'Converts a value to integer',
        category: 'coerce',
        example: 'to_int!("42") // 42',
    },
    to_regex: {
        name: 'to_regex',
        parameters: [{ name: 'value', type: 'string' }],
        returnType: 'regex',
        fallible: true,
        description: 'Converts a string to a regex pattern',
        category: 'coerce',
        example: 'to_regex!("a+b") // regex pattern',
    },
    to_string: {
        name: 'to_string',
        parameters: [{ name: 'value', type: 'any' }],
        returnType: 'string',
        fallible: false,
        description: 'Converts a value to string',
        category: 'coerce',
        example: 'to_string(42) // "42"',
    },
    to_timestamp: {
        name: 'to_timestamp',
        parameters: [
            { name: 'value', type: 'any' },
            { name: 'format', type: 'string', optional: true },
        ],
        returnType: 'timestamp',
        fallible: true,
        description: 'Converts a value to timestamp',
        category: 'coerce',
        example: 'to_timestamp!("2023-01-01T00:00:00Z")',
    },

    // Enrichment Functions
    find_enrichment_table_records: {
        name: 'find_enrichment_table_records',
        parameters: [
            { name: 'table', type: 'string' },
            { name: 'condition', type: 'object' },
            { name: 'select', type: 'array', optional: true },
            { name: 'case_sensitive', type: 'bool', optional: true },
        ],
        returnType: 'array',
        fallible: false,
        description: 'Searches an enrichment table for all records matching a condition',
        category: 'enrichment',
        example: 'find_enrichment_table_records("my_table", {"status": .status})',
    },
    get_enrichment_table_record: {
        name: 'get_enrichment_table_record',
        parameters: [
            { name: 'table', type: 'string' },
            { name: 'condition', type: 'object' },
            { name: 'select', type: 'array', optional: true },
            { name: 'case_sensitive', type: 'bool', optional: true },
        ],
        returnType: 'object',
        fallible: true,
        description: 'Searches an enrichment table for the first record matching a condition',
        category: 'enrichment',
        example: 'get_enrichment_table_record!("my_table", {"id": .id})',
    },

    // Enumerate Functions
    for_each: {
        name: 'for_each',
        parameters: [
            { name: 'value', type: 'object|array' },
            { name: 'recursive', type: 'bool', optional: true },
        ],
        returnType: 'null',
        fallible: false,
        description: 'Iterates over each item in an array or object, applying a closure',
        category: 'enumerate',
        example: 'for_each([1, 2, 3]) -> |_index, value| { log(value) }',
    },
    includes: {
        name: 'includes',
        parameters: [
            { name: 'value', type: 'array' },
            { name: 'item', type: 'any' },
        ],
        returnType: 'bool',
        fallible: false,
        description: 'Returns true if the array contains the given item',
        category: 'enumerate',
        example: 'includes([1, 2, 3], 2) // true',
    },
    map_keys: {
        name: 'map_keys',
        parameters: [
            { name: 'value', type: 'object' },
            { name: 'recursive', type: 'bool', optional: true },
        ],
        returnType: 'object',
        fallible: false,
        description: 'Transforms the keys of an object using a closure',
        category: 'enumerate',
        example: 'map_keys({"foo": 1}) -> |key| { upcase(key) } // {"FOO": 1}',
    },
    map_values: {
        name: 'map_values',
        parameters: [
            { name: 'value', type: 'object|array' },
            { name: 'recursive', type: 'bool', optional: true },
        ],
        returnType: 'object|array',
        fallible: false,
        description: 'Transforms the values of an object or array using a closure',
        category: 'enumerate',
        example: 'map_values({"a": 1, "b": 2}) -> |v| { v * 2 } // {"a": 2, "b": 4}',
    },
    match_array: {
        name: 'match_array',
        parameters: [
            { name: 'value', type: 'array' },
            { name: 'pattern', type: 'regex' },
            { name: 'all', type: 'bool', optional: true },
        ],
        returnType: 'bool',
        fallible: false,
        description: 'Returns true if any (or all) string elements of an array match the regex',
        category: 'enumerate',
        example: 'match_array(["foo", "bar"], r"foo") // true',
    },
    tally: {
        name: 'tally',
        parameters: [{ name: 'value', type: 'array' }],
        returnType: 'object',
        fallible: false,
        description: 'Counts the number of occurrences of each value in an array',
        category: 'enumerate',
        example: 'tally(["a", "b", "a"]) // {"a": 2, "b": 1}',
    },
    tally_value: {
        name: 'tally_value',
        parameters: [
            { name: 'array', type: 'array' },
            { name: 'value', type: 'any' },
        ],
        returnType: 'int',
        fallible: false,
        description: 'Counts the number of times a specific value appears in an array',
        category: 'enumerate',
        example: 'tally_value(["a", "b", "a"], "a") // 2',
    },
    unflatten: {
        name: 'unflatten',
        parameters: [
            { name: 'value', type: 'object' },
            { name: 'separator', type: 'string', optional: true },
            { name: 'recursive', type: 'bool', optional: true },
        ],
        returnType: 'object',
        fallible: false,
        description: 'Converts a flat object with dot-notation keys into a nested object',
        category: 'enumerate',
        example: 'unflatten({"a.b": 1}) // {"a": {"b": 1}}',
    },

    // Event Functions
    get_secret: {
        name: 'get_secret',
        parameters: [{ name: 'key', type: 'string' }],
        returnType: 'string|null',
        fallible: false,
        description: 'Returns the value of a secret by key from the event secrets store',
        category: 'event',
        example: 'get_secret("my_secret_key")',
    },
    remove_secret: {
        name: 'remove_secret',
        parameters: [{ name: 'key', type: 'string' }],
        returnType: 'null',
        fallible: false,
        description: 'Removes a secret by key from the event secrets store',
        category: 'event',
        example: 'remove_secret("my_secret_key")',
    },

    // IP Functions
    ip_aton: {
        name: 'ip_aton',
        parameters: [{ name: 'value', type: 'string' }],
        returnType: 'string',
        fallible: true,
        description: 'Converts an IPv4 address in dotted-decimal notation to a 4-byte representation',
        category: 'ip',
        example: 'ip_aton!("192.168.0.1")',
    },
    ip_cidr_contains: {
        name: 'ip_cidr_contains',
        parameters: [
            { name: 'cidr', type: 'string' },
            { name: 'ip', type: 'string' },
        ],
        returnType: 'bool',
        fallible: true,
        description: 'Returns true if the IP address is contained within the CIDR block',
        category: 'ip',
        example: 'ip_cidr_contains!("192.168.0.0/24", "192.168.0.1") // true',
    },
    ip_ntoa: {
        name: 'ip_ntoa',
        parameters: [{ name: 'value', type: 'string' }],
        returnType: 'string',
        fallible: true,
        description: 'Converts a 4-byte binary IPv4 address to dotted-decimal notation',
        category: 'ip',
        example: 'ip_ntoa!(.binary_ip)',
    },
    ip_ntop: {
        name: 'ip_ntop',
        parameters: [{ name: 'value', type: 'string' }],
        returnType: 'string',
        fallible: true,
        description: 'Converts a binary IP address (4 or 16 bytes) to a string representation',
        category: 'ip',
        example: 'ip_ntop!(.binary_ip)',
    },
    ip_pton: {
        name: 'ip_pton',
        parameters: [{ name: 'value', type: 'string' }],
        returnType: 'string',
        fallible: true,
        description: 'Converts an IP address string to its binary representation',
        category: 'ip',
        example: 'ip_pton!("192.168.0.1")',
    },
    ip_subnet: {
        name: 'ip_subnet',
        parameters: [
            { name: 'value', type: 'string' },
            { name: 'subnet', type: 'string' },
        ],
        returnType: 'string',
        fallible: true,
        description: 'Returns the subnet address for an IP address given a subnet mask or prefix length',
        category: 'ip',
        example: 'ip_subnet!("192.168.10.1", "255.255.255.0") // "192.168.10.0"',
    },
    ip_to_ipv6: {
        name: 'ip_to_ipv6',
        parameters: [{ name: 'value', type: 'string' }],
        returnType: 'string',
        fallible: true,
        description: 'Converts an IPv4 address to an IPv4-mapped IPv6 address',
        category: 'ip',
        example: 'ip_to_ipv6!("192.168.0.1") // "::ffff:192.168.0.1"',
    },
    ipv6_to_ipv4: {
        name: 'ipv6_to_ipv4',
        parameters: [{ name: 'value', type: 'string' }],
        returnType: 'string',
        fallible: true,
        description: 'Converts an IPv4-mapped IPv6 address to an IPv4 address',
        category: 'ip',
        example: 'ipv6_to_ipv4!("::ffff:192.168.0.1") // "192.168.0.1"',
    },
    is_ipv4: {
        name: 'is_ipv4',
        parameters: [{ name: 'value', type: 'string' }],
        returnType: 'bool',
        fallible: false,
        description: 'Returns true if the string is a valid IPv4 address',
        category: 'ip',
        example: 'is_ipv4("192.168.0.1") // true',
    },
    is_ipv6: {
        name: 'is_ipv6',
        parameters: [{ name: 'value', type: 'string' }],
        returnType: 'bool',
        fallible: false,
        description: 'Returns true if the string is a valid IPv6 address',
        category: 'ip',
        example: 'is_ipv6("::1") // true',
    },

    // String Functions
    contains: {
        name: 'contains',
        parameters: [
            { name: 'text', type: 'string' },
            { name: 'substring', type: 'string' },
        ],
        returnType: 'bool',
        fallible: false,
        description: 'Checks if text contains substring',
        category: 'string',
        example: 'contains("hello world", "world") // true',
    },
    downcase: {
        name: 'downcase',
        parameters: [{ name: 'text', type: 'string' }],
        returnType: 'string',
        fallible: false,
        description: 'Converts text to lowercase',
        category: 'string',
        example: 'downcase("HELLO") // "hello"',
    },
    ends_with: {
        name: 'ends_with',
        parameters: [
            { name: 'text', type: 'string' },
            { name: 'suffix', type: 'string' },
        ],
        returnType: 'bool',
        fallible: false,
        description: 'Checks if text ends with suffix',
        category: 'string',
        example: 'ends_with("hello.txt", ".txt") // true',
    },
    match: {
        name: 'match',
        parameters: [
            { name: 'text', type: 'string' },
            { name: 'pattern', type: 'regex' },
        ],
        returnType: 'bool',
        fallible: false,
        description: 'Checks if text matches regex pattern',
        category: 'string',
        example: 'match("abc123", r"\\d+") // true',
    },
    replace: {
        name: 'replace',
        parameters: [
            { name: 'text', type: 'string' },
            { name: 'pattern', type: 'string|regex' },
            { name: 'replacement', type: 'string' },
        ],
        returnType: 'string',
        fallible: false,
        description: 'Replaces pattern matches in text',
        category: 'string',
        example: 'replace("hello world", "world", "VRL") // "hello VRL"',
    },
    split: {
        name: 'split',
        parameters: [
            { name: 'text', type: 'string' },
            { name: 'delimiter', type: 'string' },
        ],
        returnType: 'array',
        fallible: false,
        description: 'Splits text by delimiter',
        category: 'string',
        example: 'split("a,b,c", ",") // ["a", "b", "c"]',
    },
    starts_with: {
        name: 'starts_with',
        parameters: [
            { name: 'text', type: 'string' },
            { name: 'prefix', type: 'string' },
        ],
        returnType: 'bool',
        fallible: false,
        description: 'Checks if text starts with prefix',
        category: 'string',
        example: 'starts_with("hello.txt", "hello") // true',
    },
    capitalize: {
        name: 'capitalize',
        parameters: [{ name: 'value', type: 'string' }],
        returnType: 'string',
        fallible: false,
        description: 'Converts the first character of the string to uppercase',
        category: 'string',
        example: 'capitalize("hello world") // "Hello world"',
    },
    find: {
        name: 'find',
        parameters: [
            { name: 'value', type: 'string' },
            { name: 'pattern', type: 'string|regex' },
            { name: 'from', type: 'int', optional: true },
        ],
        returnType: 'int',
        fallible: false,
        description: 'Returns the index of the first occurrence of a pattern in the string, or -1 if not found',
        category: 'string',
        example: 'find("hello world", "world") // 6',
    },
    indent: {
        name: 'indent',
        parameters: [
            { name: 'value', type: 'string' },
            { name: 'indent', type: 'string' },
        ],
        returnType: 'string',
        fallible: false,
        description: 'Prepends the indent string to each line of the string',
        category: 'string',
        example: 'indent("line1\\nline2", "  ") // "  line1\\n  line2"',
    },
    ltrimstr: {
        name: 'ltrimstr',
        parameters: [
            { name: 'value', type: 'string' },
            { name: 'substring', type: 'string' },
        ],
        returnType: 'string',
        fallible: false,
        description: 'Removes a prefix from a string if present',
        category: 'string',
        example: 'ltrimstr("hello world", "hello ") // "world"',
    },
    match_datadog_query: {
        name: 'match_datadog_query',
        parameters: [
            { name: 'value', type: 'object' },
            { name: 'query', type: 'string' },
        ],
        returnType: 'bool',
        fallible: true,
        description: 'Returns true if the event object matches the Datadog search query',
        category: 'string',
        example: 'match_datadog_query!(.event, "status:error")',
    },
    rtrimstr: {
        name: 'rtrimstr',
        parameters: [
            { name: 'value', type: 'string' },
            { name: 'substring', type: 'string' },
        ],
        returnType: 'string',
        fallible: false,
        description: 'Removes a suffix from a string if present',
        category: 'string',
        example: 'rtrimstr("hello world", " world") // "hello"',
    },
    truncate: {
        name: 'truncate',
        parameters: [
            { name: 'value', type: 'string' },
            { name: 'limit', type: 'int' },
            { name: 'suffix', type: 'string', optional: true },
        ],
        returnType: 'string',
        fallible: false,
        description: 'Truncates a string to the specified character limit, optionally appending a suffix',
        category: 'string',
        example: 'truncate("hello world", 5, "...") // "hello..."',
    },
    strip_ansi_escape_codes: {
        name: 'strip_ansi_escape_codes',
        parameters: [{ name: 'text', type: 'string' }],
        returnType: 'string',
        fallible: false,
        description: 'Removes ANSI escape codes from text',
        category: 'string',
        example: 'strip_ansi_escape_codes("\\x1b[31mred\\x1b[0m") // "red"',
    },
    strip_whitespace: {
        name: 'strip_whitespace',
        parameters: [{ name: 'text', type: 'string' }],
        returnType: 'string',
        fallible: false,
        description: 'Removes leading and trailing whitespace',
        category: 'string',
        example: 'strip_whitespace("  hello  ") // "hello"',
    },
    strlen: {
        name: 'strlen',
        parameters: [{ name: 'text', type: 'string' }],
        returnType: 'int',
        fallible: false,
        description: 'Returns the character length of a string',
        category: 'string',
        example: 'strlen("hello") // 5',
    },
    upcase: {
        name: 'upcase',
        parameters: [{ name: 'text', type: 'string' }],
        returnType: 'string',
        fallible: false,
        description: 'Converts text to uppercase',
        category: 'string',
        example: 'upcase("hello") // "HELLO"',
    },

    // Parsing Functions (MOSTLY FALLIBLE)
    parse_apache_log: {
        name: 'parse_apache_log',
        parameters: [
            { name: 'message', type: 'string' },
            { name: 'format', type: 'string', optional: true },
        ],
        returnType: 'object',
        fallible: true,
        description: 'Parses Apache access logs',
        category: 'parse',
        example: 'parse_apache_log!(.message)',
    },
    parse_cef: {
        name: 'parse_cef',
        parameters: [
            { name: 'message', type: 'string' },
            { name: 'transform_fields', type: 'bool', optional: true },
        ],
        returnType: 'object',
        fallible: true,
        description: 'Parses Common Event Format (CEF) messages',
        category: 'parse',
        example: 'parse_cef!(.message)',
    },
    parse_common_log: {
        name: 'parse_common_log',
        parameters: [{ name: 'message', type: 'string' }],
        returnType: 'object',
        fallible: true,
        description: 'Parses Common Log Format messages',
        category: 'parse',
        example: 'parse_common_log!(.message)',
    },
    parse_csv: {
        name: 'parse_csv',
        parameters: [
            { name: 'text', type: 'string' },
            { name: 'delimiter', type: 'string', optional: true },
        ],
        returnType: 'array',
        fallible: true,
        description: 'Parses CSV formatted text',
        category: 'parse',
        example: 'parse_csv!(.text, ",")',
    },
    parse_grok: {
        name: 'parse_grok',
        parameters: [
            { name: 'text', type: 'string' },
            { name: 'pattern', type: 'string' },
        ],
        returnType: 'object',
        fallible: true,
        description: 'Parses text using Grok patterns',
        category: 'parse',
        example: 'parse_grok!(.message, "%{COMMONAPACHELOG}")',
    },
    parse_groks: {
        name: 'parse_groks',
        parameters: [
            { name: 'text', type: 'string' },
            { name: 'patterns', type: 'array' },
        ],
        returnType: 'object',
        fallible: true,
        description: 'Parses text using multiple Grok patterns',
        category: 'parse',
        example: 'parse_groks!(.message, ["%{COMMONAPACHELOG}", "%{COMBINEDAPACHELOG}"])',
    },
    parse_json: {
        name: 'parse_json',
        parameters: [{ name: 'text', type: 'string' }],
        returnType: 'any',
        fallible: true,
        description: 'Parses JSON formatted text',
        category: 'parse',
        example: 'parse_json!(.message)',
    },
    parse_key_value: {
        name: 'parse_key_value',
        parameters: [
            { name: 'text', type: 'string' },
            { name: 'separator', type: 'string', optional: true },
            { name: 'delimiter', type: 'string', optional: true },
        ],
        returnType: 'object',
        fallible: true,
        description: 'Parses key-value pairs from text',
        category: 'parse',
        example: 'parse_key_value!(.message, "=", " ")',
    },
    parse_nginx_log: {
        name: 'parse_nginx_log',
        parameters: [
            { name: 'message', type: 'string' },
            { name: 'format', type: 'string', optional: true },
        ],
        returnType: 'object',
        fallible: true,
        description: 'Parses Nginx access logs',
        category: 'parse',
        example: 'parse_nginx_log!(.message)',
    },
    parse_regex: {
        name: 'parse_regex',
        parameters: [
            { name: 'text', type: 'string' },
            { name: 'pattern', type: 'regex' },
        ],
        returnType: 'object',
        fallible: true,
        description: 'Parses text using regex with named capture groups',
        category: 'parse',
        example: 'parse_regex!(.message, r"(?P<level>\\w+): (?P<msg>.*)")',
    },
    parse_syslog: {
        name: 'parse_syslog',
        parameters: [{ name: 'message', type: 'string' }],
        returnType: 'object',
        fallible: true,
        description: 'Parses syslog formatted messages',
        category: 'parse',
        example: 'parse_syslog!(.message)',
    },
    parse_timestamp: {
        name: 'parse_timestamp',
        parameters: [
            { name: 'text', type: 'string' },
            { name: 'format', type: 'string' },
        ],
        returnType: 'timestamp',
        fallible: true,
        description: 'Parses timestamp from text using format string',
        category: 'parse',
        example: 'parse_timestamp!(.date, "%Y-%m-%d %H:%M:%S")',
    },
    parse_url: {
        name: 'parse_url',
        parameters: [{ name: 'url', type: 'string' }],
        returnType: 'object',
        fallible: true,
        description: 'Parses URL into components',
        category: 'parse',
        example: 'parse_url!("https://example.com/path?query=value")',
    },
    parse_user_agent: {
        name: 'parse_user_agent',
        parameters: [{ name: 'user_agent', type: 'string' }],
        returnType: 'object',
        fallible: true,
        description: 'Parses User-Agent string into components',
        category: 'parse',
        example: 'parse_user_agent!(.user_agent)',
    },
    parse_aws_alb_log: {
        name: 'parse_aws_alb_log',
        parameters: [{ name: 'value', type: 'string' }],
        returnType: 'object',
        fallible: true,
        description: 'Parses an AWS Application Load Balancer (ALB) access log line',
        category: 'parse',
        example: 'parse_aws_alb_log!(.message)',
    },
    parse_aws_cloudwatch_log_subscription_message: {
        name: 'parse_aws_cloudwatch_log_subscription_message',
        parameters: [{ name: 'value', type: 'string' }],
        returnType: 'object',
        fallible: true,
        description: 'Parses an AWS CloudWatch log subscription message',
        category: 'parse',
        example: 'parse_aws_cloudwatch_log_subscription_message!(.message)',
    },
    parse_duration: {
        name: 'parse_duration',
        parameters: [
            { name: 'value', type: 'string' },
            { name: 'unit', type: 'string' },
        ],
        returnType: 'float',
        fallible: true,
        description: 'Parses a duration string (e.g. "1h30m") and converts it to the specified unit',
        category: 'parse',
        example: 'parse_duration!("1h30m", "s") // 5400.0',
    },
    parse_glog: {
        name: 'parse_glog',
        parameters: [{ name: 'value', type: 'string' }],
        returnType: 'object',
        fallible: true,
        description: 'Parses a Google (glog) formatted log line',
        category: 'parse',
        example: 'parse_glog!(.message)',
    },
    parse_klog: {
        name: 'parse_klog',
        parameters: [{ name: 'value', type: 'string' }],
        returnType: 'object',
        fallible: true,
        description: 'Parses a Kubernetes (klog) formatted log line',
        category: 'parse',
        example: 'parse_klog!(.message)',
    },
    parse_linux_authorization: {
        name: 'parse_linux_authorization',
        parameters: [{ name: 'value', type: 'string' }],
        returnType: 'object',
        fallible: true,
        description: 'Parses a Linux authorization log line (e.g. /var/log/auth.log)',
        category: 'parse',
        example: 'parse_linux_authorization!(.message)',
    },
    parse_logfmt: {
        name: 'parse_logfmt',
        parameters: [{ name: 'value', type: 'string' }],
        returnType: 'object',
        fallible: true,
        description: 'Parses a logfmt formatted string into key-value pairs',
        category: 'parse',
        example: 'parse_logfmt!("level=info msg=hello") // {"level": "info", "msg": "hello"}',
    },
    parse_query_string: {
        name: 'parse_query_string',
        parameters: [{ name: 'value', type: 'string' }],
        returnType: 'object',
        fallible: true,
        description: 'Parses a URL query string into an object of key-value pairs',
        category: 'parse',
        example: 'parse_query_string!("key=value&foo=bar") // {"key": "value", "foo": "bar"}',
    },
    parse_regex_all: {
        name: 'parse_regex_all',
        parameters: [
            { name: 'value', type: 'string' },
            { name: 'pattern', type: 'regex' },
        ],
        returnType: 'array',
        fallible: true,
        description: 'Extracts all non-overlapping regex matches from a string as an array of objects',
        category: 'parse',
        example: 'parse_regex_all!("foo bar baz", r"(?P<word>\\w+)")',
    },
    parse_ruby_hash: {
        name: 'parse_ruby_hash',
        parameters: [{ name: 'value', type: 'string' }],
        returnType: 'object',
        fallible: true,
        description: 'Parses a Ruby Hash formatted string into an object',
        category: 'parse',
        example: 'parse_ruby_hash!("{:key => \\"value\\"}")',
    },
    parse_tokens: {
        name: 'parse_tokens',
        parameters: [{ name: 'value', type: 'string' }],
        returnType: 'array',
        fallible: true,
        description: 'Parses a string into an array of tokens separated by whitespace (handles quoted strings)',
        category: 'parse',
        example: 'parse_tokens!("foo \\"bar baz\\" qux") // ["foo", "bar baz", "qux"]',
    },
    parse_xml: {
        name: 'parse_xml',
        parameters: [
            { name: 'value', type: 'string' },
            { name: 'trim', type: 'bool', optional: true },
            { name: 'include_attr', type: 'bool', optional: true },
            { name: 'attr_prefix', type: 'string', optional: true },
            { name: 'text_key', type: 'string', optional: true },
            { name: 'always_use_text_key', type: 'bool', optional: true },
            { name: 'parse_number', type: 'bool', optional: true },
            { name: 'parse_bool', type: 'bool', optional: true },
            { name: 'parse_null', type: 'bool', optional: true },
        ],
        returnType: 'object',
        fallible: true,
        description: 'Parses an XML string into an object',
        category: 'parse',
        example: 'parse_xml!("<root><key>value</key></root>")',
    },

    // Random Functions
    random_bool: {
        name: 'random_bool',
        parameters: [],
        returnType: 'bool',
        fallible: false,
        description: 'Returns a random boolean value',
        category: 'random',
        example: 'random_bool() // true or false',
    },
    random_float: {
        name: 'random_float',
        parameters: [
            { name: 'min', type: 'float', optional: true },
            { name: 'max', type: 'float', optional: true },
        ],
        returnType: 'float',
        fallible: false,
        description: 'Returns a random float, optionally within a specified range',
        category: 'random',
        example: 'random_float(min: 0.0, max: 1.0)',
    },
    random_int: {
        name: 'random_int',
        parameters: [
            { name: 'min', type: 'int', optional: true },
            { name: 'max', type: 'int', optional: true },
        ],
        returnType: 'int',
        fallible: false,
        description: 'Returns a random integer, optionally within a specified range',
        category: 'random',
        example: 'random_int(min: 1, max: 100)',
    },

    // System Functions
    env_var: {
        name: 'env_var',
        parameters: [{ name: 'name', type: 'string' }],
        returnType: 'string',
        fallible: true,
        description: 'Returns the value of the named environment variable',
        category: 'system',
        example: 'env_var!("HOME")',
    },
    hostname: {
        name: 'hostname',
        parameters: [],
        returnType: 'string',
        fallible: true,
        description: 'Returns the hostname of the system',
        category: 'system',
        example: 'hostname!()',
    },

    // Cryptographic/Hash Functions
    decrypt: {
        name: 'decrypt',
        parameters: [
            { name: 'ciphertext', type: 'string' },
            { name: 'algorithm', type: 'string' },
            { name: 'key', type: 'string' },
            { name: 'iv', type: 'string', optional: true },
        ],
        returnType: 'string',
        fallible: true,
        description: 'Decrypts ciphertext using specified algorithm',
        category: 'crypto',
        example: 'decrypt!(.ciphertext, "AES-256-GCM", .key, .iv)',
    },
    hmac: {
        name: 'hmac',
        parameters: [
            { name: 'message', type: 'string' },
            { name: 'key', type: 'string' },
            { name: 'algorithm', type: 'string', optional: true },
        ],
        returnType: 'string',
        fallible: false,
        description: 'Generates HMAC hash',
        category: 'crypto',
        example: 'hmac("message", "secret", "sha256")',
    },
    md5: {
        name: 'md5',
        parameters: [{ name: 'text', type: 'string' }],
        returnType: 'string',
        fallible: false,
        description: 'Generates MD5 hash',
        category: 'crypto',
        example: 'md5("hello") // "5d41402abc4b2a76b9719d911017c592"',
    },
    sha1: {
        name: 'sha1',
        parameters: [{ name: 'text', type: 'string' }],
        returnType: 'string',
        fallible: false,
        description: 'Generates SHA1 hash',
        category: 'crypto',
        example: 'sha1("hello")',
    },
    sha2: {
        name: 'sha2',
        parameters: [
            { name: 'text', type: 'string' },
            { name: 'variant', type: 'int', optional: true },
        ],
        returnType: 'string',
        fallible: false,
        description: 'Generates SHA2 hash (SHA-256 by default)',
        category: 'crypto',
        example: 'sha2("hello", 256)',
    },
    sha3: {
        name: 'sha3',
        parameters: [
            { name: 'text', type: 'string' },
            { name: 'variant', type: 'int', optional: true },
        ],
        returnType: 'string',
        fallible: false,
        description: 'Generates SHA3 hash',
        category: 'crypto',
        example: 'sha3("hello", 256)',
    },
    encrypt: {
        name: 'encrypt',
        parameters: [
            { name: 'plaintext', type: 'string' },
            { name: 'algorithm', type: 'string' },
            { name: 'key', type: 'string' },
            { name: 'iv', type: 'string', optional: true },
        ],
        returnType: 'string',
        fallible: true,
        description: 'Encrypts plaintext using the specified algorithm and key',
        category: 'crypto',
        example: 'encrypt!("secret", "AES-256-GCM", .key, .iv)',
    },

    // Date/Time Functions
    format_timestamp: {
        name: 'format_timestamp',
        parameters: [
            { name: 'timestamp', type: 'timestamp' },
            { name: 'format', type: 'string' },
        ],
        returnType: 'string',
        fallible: true,
        description: 'Formats timestamp as string',
        category: 'datetime',
        example: 'format_timestamp!(.timestamp, "%Y-%m-%d %H:%M:%S")',
    },
    from_unix_timestamp: {
        name: 'from_unix_timestamp',
        parameters: [
            { name: 'unix_timestamp', type: 'int' },
            { name: 'unit', type: 'string', optional: true },
        ],
        returnType: 'timestamp',
        fallible: false,
        description: 'Converts Unix timestamp to timestamp',
        category: 'datetime',
        example: 'from_unix_timestamp(1640995200, "seconds")',
    },
    now: {
        name: 'now',
        parameters: [],
        returnType: 'timestamp',
        fallible: false,
        description: 'Returns current timestamp',
        category: 'datetime',
        example: 'now()',
    },
    to_unix_timestamp: {
        name: 'to_unix_timestamp',
        parameters: [
            { name: 'timestamp', type: 'timestamp' },
            { name: 'unit', type: 'string', optional: true },
        ],
        returnType: 'int',
        fallible: false,
        description: 'Converts timestamp to Unix timestamp',
        category: 'datetime',
        example: 'to_unix_timestamp(.timestamp, "seconds")',
    },

    // Object/Path Functions
    del: {
        name: 'del',
        parameters: [{ name: 'path', type: 'path' }],
        returnType: 'null',
        fallible: false,
        description: 'Deletes a field from the event',
        category: 'object',
        example: 'del(.field_to_remove)',
    },
    exists: {
        name: 'exists',
        parameters: [{ name: 'path', type: 'path' }],
        returnType: 'bool',
        fallible: false,
        description: 'Checks if a field exists',
        category: 'object',
        example: 'exists(.optional_field)',
    },
    get: {
        name: 'get',
        parameters: [
            { name: 'object', type: 'object' },
            { name: 'path', type: 'path' },
            { name: 'default', type: 'any', optional: true },
        ],
        returnType: 'any',
        fallible: false,
        description: 'Gets value from object at path with optional default',
        category: 'object',
        example: 'get(.data, ["nested", "field"], "default")',
    },
    has: {
        name: 'has',
        parameters: [
            { name: 'object', type: 'object' },
            { name: 'field', type: 'string' },
        ],
        returnType: 'bool',
        fallible: false,
        description: 'Checks if object has field',
        category: 'object',
        example: 'has(.metadata, "version")',
    },
    keys: {
        name: 'keys',
        parameters: [{ name: 'object', type: 'object' }],
        returnType: 'array',
        fallible: false,
        description: 'Returns array of object keys',
        category: 'object',
        example: 'keys(.metadata) // ["key1", "key2"]',
    },
    merge: {
        name: 'merge',
        parameters: [
            { name: 'object1', type: 'object' },
            { name: 'object2', type: 'object' },
            { name: 'deep', type: 'bool', optional: true },
        ],
        returnType: 'object',
        fallible: false,
        description: 'Merges two objects',
        category: 'object',
        example: 'merge(.obj1, .obj2, true)',
    },
    remove: {
        name: 'remove',
        parameters: [
            { name: 'object', type: 'object' },
            { name: 'path', type: 'path' },
            { name: 'compact', type: 'bool', optional: true },
        ],
        returnType: 'any',
        fallible: false,
        description: 'Removes field from object and returns its value',
        category: 'object',
        example: 'remove(.metadata, .field)',
    },
    set: {
        name: 'set',
        parameters: [
            { name: 'object', type: 'object' },
            { name: 'path', type: 'path' },
            { name: 'value', type: 'any' },
        ],
        returnType: 'any',
        fallible: false,
        description: 'Sets value in object at path',
        category: 'object',
        example: 'set(.metadata, "version", "1.0")',
    },
    values: {
        name: 'values',
        parameters: [{ name: 'object', type: 'object' }],
        returnType: 'array',
        fallible: false,
        description: 'Returns array of object values',
        category: 'object',
        example: 'values(.metadata) // ["value1", "value2"]',
    },

    // Type Checking Functions
    array: {
        name: 'array',
        parameters: [{ name: 'value', type: 'any' }],
        returnType: 'array',
        fallible: true,
        description: 'Coerces the value into an array. Fails if the value cannot be represented as an array.',
        category: 'type',
        example: 'array!(parse_json!(.message))',
    },
    bool: {
        name: 'bool',
        parameters: [{ name: 'value', type: 'any' }],
        returnType: 'bool',
        fallible: true,
        description: 'Coerces the value into a boolean. Fails if the value is not a boolean.',
        category: 'type',
        example: 'bool!(.field)',
    },
    float: {
        name: 'float',
        parameters: [{ name: 'value', type: 'any' }],
        returnType: 'float',
        fallible: true,
        description: 'Coerces the value into a float. Fails if the value is not a float.',
        category: 'type',
        example: 'float!(.field)',
    },
    int: {
        name: 'int',
        parameters: [{ name: 'value', type: 'any' }],
        returnType: 'int',
        fallible: true,
        description: 'Coerces the value into an integer. Fails if the value is not an integer.',
        category: 'type',
        example: 'int!(.field)',
    },
    is_array: {
        name: 'is_array',
        parameters: [{ name: 'value', type: 'any' }],
        returnType: 'bool',
        fallible: false,
        description: 'Checks if value is an array',
        category: 'type',
        example: 'is_array([1, 2, 3]) // true',
    },
    is_bool: {
        name: 'is_bool',
        parameters: [{ name: 'value', type: 'any' }],
        returnType: 'bool',
        fallible: false,
        description: 'Checks if value is a boolean',
        category: 'type',
        example: 'is_bool(true) // true',
    },
    is_float: {
        name: 'is_float',
        parameters: [{ name: 'value', type: 'any' }],
        returnType: 'bool',
        fallible: false,
        description: 'Checks if value is a float',
        category: 'type',
        example: 'is_float(3.14) // true',
    },
    is_int: {
        name: 'is_int',
        parameters: [{ name: 'value', type: 'any' }],
        returnType: 'bool',
        fallible: false,
        description: 'Checks if value is an integer',
        category: 'type',
        example: 'is_int(42) // true',
    },
    is_null: {
        name: 'is_null',
        parameters: [{ name: 'value', type: 'any' }],
        returnType: 'bool',
        fallible: false,
        description: 'Checks if value is null',
        category: 'type',
        example: 'is_null(null) // true',
    },
    is_object: {
        name: 'is_object',
        parameters: [{ name: 'value', type: 'any' }],
        returnType: 'bool',
        fallible: false,
        description: 'Checks if value is an object',
        category: 'type',
        example: 'is_object({"key": "value"}) // true',
    },
    is_string: {
        name: 'is_string',
        parameters: [{ name: 'value', type: 'any' }],
        returnType: 'bool',
        fallible: false,
        description: 'Checks if value is a string',
        category: 'type',
        example: 'is_string("hello") // true',
    },
    is_timestamp: {
        name: 'is_timestamp',
        parameters: [{ name: 'value', type: 'any' }],
        returnType: 'bool',
        fallible: false,
        description: 'Checks if value is a timestamp',
        category: 'type',
        example: 'is_timestamp(now()) // true',
    },
    is_nullish: {
        name: 'is_nullish',
        parameters: [{ name: 'value', type: 'any' }],
        returnType: 'bool',
        fallible: false,
        description: 'Returns true if value is null, an empty string, or a whitespace-only string',
        category: 'type',
        example: 'is_nullish(null) // true\nis_nullish("  ") // true',
    },
    is_regex: {
        name: 'is_regex',
        parameters: [{ name: 'value', type: 'any' }],
        returnType: 'bool',
        fallible: false,
        description: 'Returns true if the value is a regex type',
        category: 'type',
        example: 'is_regex(r"\\d+") // true',
    },
    object: {
        name: 'object',
        parameters: [{ name: 'value', type: 'any' }],
        returnType: 'object',
        fallible: true,
        description: 'Coerces the value into an object. Fails if the value is not an object.',
        category: 'type',
        example: 'object!(.field)',
    },
    string: {
        name: 'string',
        parameters: [{ name: 'value', type: 'any' }],
        returnType: 'string',
        fallible: true,
        description: 'Coerces the value into a string. Fails if the value is not a string.',
        category: 'coerce',
        example: 'string!(.field)',
    },
    timestamp: {
        name: 'timestamp',
        parameters: [{ name: 'value', type: 'any' }],
        returnType: 'timestamp',
        fallible: true,
        description: 'Coerces the value into an timestamp. Fails if the value is not an timestamp.',
        category: 'type',
        example: 'timestamp!(.field)',
    },
    type_def: {
        name: 'timestamp',
        parameters: [{ name: 'value', type: 'any' }],
        returnType: 'timestamp',
        fallible: false,
        description: 'Returns the type definition of an expression at runtime.',
        category: 'type',
        example: 'type_def(.field)',
    },

    // Utility Functions
    assert: {
        name: 'assert',
        parameters: [
            { name: 'condition', type: 'bool' },
            { name: 'message', type: 'string', optional: true },
        ],
        returnType: 'null',
        fallible: true,
        description: 'Asserts that condition is true, aborts if false',
        category: 'utility',
        example: 'assert!(exists(.required_field), "Missing required field")',
    },
    assert_eq: {
        name: 'assert_eq',
        parameters: [
            { name: 'left', type: 'any' },
            { name: 'right', type: 'any' },
            { name: 'message', type: 'string', optional: true },
        ],
        returnType: 'null',
        fallible: true,
        description: 'Asserts that two values are equal',
        category: 'utility',
        example: 'assert_eq!(.status, 200, "Expected 200 status")',
    },
    log: {
        name: 'log',
        parameters: [
            { name: 'message', type: 'string' },
            { name: 'level', type: 'string', optional: true },
        ],
        returnType: 'null',
        fallible: false,
        description: 'Logs a message at specified level',
        category: 'utility',
        example: 'log("Processing event", level: "debug")',
    },
    type: {
        name: 'type',
        parameters: [{ name: 'value', type: 'any' }],
        returnType: 'string',
        fallible: false,
        description: 'Returns the type name of a value',
        category: 'utility',
        example: 'type("hello") // "string"',
    },
    uuid_v4: {
        name: 'uuid_v4',
        parameters: [],
        returnType: 'string',
        fallible: false,
        description: 'Generates a random UUID v4',
        category: 'utility',
        example: 'uuid_v4() // "550e8400-e29b-41d4-a716-446655440000"',
    },
    uuid_v7: {
        name: 'uuid_v7',
        parameters: [{ name: 'timestamp', type: 'timestamp', optional: true }],
        returnType: 'string',
        fallible: false,
        description: 'Generates a time-ordered UUID v7, optionally based on a given timestamp',
        category: 'utility',
        example: 'uuid_v7()',
    },

    // Math Functions
    abs: {
        name: 'abs',
        parameters: [{ name: 'value', type: 'int|float' }],
        returnType: 'int|float',
        fallible: false,
        description: 'Returns absolute value',
        category: 'math',
        example: 'abs(-5) // 5',
    },
    ceil: {
        name: 'ceil',
        parameters: [{ name: 'value', type: 'float' }],
        returnType: 'int',
        fallible: false,
        description: 'Rounds up to nearest integer',
        category: 'math',
        example: 'ceil(3.2) // 4',
    },
    floor: {
        name: 'floor',
        parameters: [{ name: 'value', type: 'float' }],
        returnType: 'int',
        fallible: false,
        description: 'Rounds down to nearest integer',
        category: 'math',
        example: 'floor(3.8) // 3',
    },
    max: {
        name: 'max',
        parameters: [{ name: 'array', type: 'array' }],
        returnType: 'int|float',
        fallible: true,
        description: 'Returns maximum value from array',
        category: 'math',
        example: 'max!([1, 2, 3]) // 3',
    },
    min: {
        name: 'min',
        parameters: [{ name: 'array', type: 'array' }],
        returnType: 'int|float',
        fallible: true,
        description: 'Returns minimum value from array',
        category: 'math',
        example: 'min!([1, 2, 3]) // 1',
    },
    round: {
        name: 'round',
        parameters: [
            { name: 'value', type: 'float' },
            { name: 'precision', type: 'int', optional: true },
        ],
        returnType: 'float',
        fallible: false,
        description: 'Rounds to specified precision',
        category: 'math',
        example: 'round(3.14159, 2) // 3.14',
    },
};

export const VRL_FUNCTION_NAMES = Object.keys(VRL_FUNCTIONS);

export const FALLIBLE_FUNCTIONS = VRL_FUNCTION_NAMES.filter((name) => VRL_FUNCTIONS[name].fallible);

export const INFALLIBLE_FUNCTIONS = VRL_FUNCTION_NAMES.filter(
    (name) => !VRL_FUNCTIONS[name].fallible
);

export function getFunctionByName(name: string): VrlFunction | undefined {
    return VRL_FUNCTIONS[name];
}

export function getFunctionsByCategory(category: string): VrlFunction[] {
    return Object.values(VRL_FUNCTIONS).filter((func) => func.category === category);
}
